export const ON_LOGIN = 'User Login'
export const TRACK_MONTHLY_SPEND = 'Track Monthly Spend'
export const HEALTH_AND_FITNESS = 'HealthAndFitness'
export const BEAUTY = 'Beauty'
export const CLOTHING = 'Clothing'
export const COSMETICS = 'Cosmetics'
export const HOUSING = 'Housing'
export const FOOD = 'Food'